#dnf module disable nodejs -y
#dnf module enable nodejs:20 -y
#
#dnf install nodejs -y
#
#useradd roboshop
#
#cp catalogue.service /etc/systemd/system/catalogue.service
#cp mongo.repo /etc/yum.repos.d/mongo.repo
#
#mkdir /app
#
#curl -o /tmp/catalogue.zip https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
#cd /app
#unzip /tmp/catalogue.zip
#
#cd /app
#npm install
#
#dnf install mongodb-mongosh -y
#mongosh --host mongod-dev.kiranpanchavati.online </app/db/master-data.js
#
#systemctl daemon-reload
#
#systemctl enable catalogue
#systemctl restart catalogue
#

- name: Catalogue Setup
  hosts: all
  become: true
  tasks:
    - name: Install NodeJS 20
      ansible.builtin.dnf:
        name: '@nodejs:20'
        state: present

    - name: Add the user 'roboshop'
      ansible.builtin.user:
        name: roboshop

    - name: Remove app directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Install unzip
      ansible.builtin.dnf:
        name: unzip
        state: present

    - name: Download and extract app content
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
        dest: /app
        remote_src: yes

    - name: Install packages based on package.json.
      community.general.npm:
        path: /app


    - name: Copy the MongoDB Repo File
      ansible.builtin.copy:
        src: mongo.repo # Path on the Ansible control machine
        dest: /etc/yum.repos.d/mongo.repo     # Path on the remote host

    - name: Load Master Data
      community.mongodb.mongodb_shell:
        login_user: user
        login_password: secret
        file: "/app/db/master-data.js"
        login_host: mongod-dev.kiranpanchavati.online
        idempotent: yes

    - name: Copy Catalogue Service file
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: Start Catalogue service
      ansible.builtin.systemd_service:
        state: restarted
        name: catalogue
        enabled: true
        daemon_reload: true
