#dnf module disable nodejs -y
#dnf module enable nodejs:20 -y
#
#dnf install nodejs -y
#
#useradd roboshop
#
#cp catalogue.service /etc/systemd/system/catalogue.service
#cp mongo.repo /etc/yum.repos.d/mongo.repo
#
#mkdir /app
#
#curl -o /tmp/catalogue.zip https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
#cd /app
#unzip /tmp/catalogue.zip
#
#cd /app
#npm install
#
#dnf install mongodb-mongosh -y
#mongosh --host mongod-dev.kiranpanchavati.online </app/db/master-data.js
#
#systemctl daemon-reload
#
#systemctl enable catalogue
#systemctl restart catalogue
#

- name: Catalogue Setup
  hosts: all
  become: true
  tasks:
    - name: Install NodeJS
      ansible.builtin.dnf:
        name: 'nodejs'
        state: present

    - name: Create a user 'roboshop' with a home directory
      ansible.builtin.user:
        name: roboshop
        create_home: yes

    - name: Copy Catalogue Service file
      ansible.builtin.copy:
        src: /root/Ansible/Ansible-RoboShop-V1/catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: Copy Mongo Repo file
      ansible.builtin.copy:
        src: /root/Ansible/Ansible-RoboShop-V1/mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Install the unzip
      ansible.builtin.dnf:
        name: unzip
        state: latest

    - name: Download and Extract
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
        dest: /app
        remote_src: yes

    - name: Run a command in /app directory
      ansible.builtin.command:
        cmd: ls -l
        chdir: /app

    - name: Install NodeJS dependencies
      ansible.builtin.command: npm install
      args:
        chdir: /app
      become_user: roboshop

    - name: Install MongoDB
      ansible.builtin.dnf:
        name: 'mongodb-mongosh'
        state: present

    - name: Load master data script
      ansible.builtin.shell: mongosh --host mongod-dev-01.kiranpanchavati.online </app/db/master-data.js

    - name: Just force systemd to reread configs (2.4 and above)
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: Start Catalogue services
      ansible.builtin.systemd_service:
        state: started
        name: catalogue
        enabled: true