#dnf module disable nginx -y
#dnf module enable nginx:1.24 -y
#dnf install nginx -y
#
#
#rm -rf /usr/share/nginx/html/*
#curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
#
#cd /usr/share/nginx/html
#unzip /tmp/frontend.zip
#
#sudo cp /root/DevSecOps-Roboshop-Shell-V1/nginx.conf /etc/nginx/nginx.conf
#
#systemctl enable nginx
#systemctl restart nginx

- name: Frontend Setup
  hosts: all
  become: true
  tasks:
    - name: Install NGINX
      ansible.builtin.dnf:
        name: 'nginx'
        state: present

    - name: Remove the default HTML Directory
      ansible.builtin.file:
        path: /usr/share/nginx/html/
        state: absent

    - name: Create a directory
      ansible.builtin.file:
        path: /usr/share/nginx/html/
        state: directory

    - name: Install the unzip
      ansible.builtin.dnf:
        name: unzip
        state: latest

    - name: Download and Extract
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: Copy nginx file
      ansible.builtin.copy:
        src: /root/nginx.conf
        dest: /etc/nginx/nginx.conf

    - name: Start NGINX services
      ansible.builtin.systemd_service:
        state: started
        name: nginx
        enabled: true