#dnf module disable nginx -y
#dnf module enable nginx:1.24 -y
#dnf install nginx -y
#
#
#rm -rf /usr/share/nginx/html/*
#curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
#
#cd /usr/share/nginx/html
#unzip /tmp/frontend.zip
#
#sudo cp /root/DevSecOps-Roboshop-Shell-V1/nginx.conf /etc/nginx/nginx.conf
#
#systemctl enable nginx
#systemctl restart nginx


# Reference Ansible Documentation
#https://docs.ansible.com/projects/ansible/latest/collections/ansible/builtin/dnf_module.html

- name: Frontend Setup
  hosts: all
  become: true
  tasks:
    - name: Install nginx 1.24-Frontend
      ansible.builtin.dnf:
        name: '@nginx:1.24'
        state: present

    - name: Remove the default HTML Directory
      ansible.builtin.file:
        path: /usr/share/nginx/html/
        state: absent

    - name: Create a directory
      ansible.builtin.file:
        path: /usr/share/nginx/html/
        state: directory

