##dnf install mysql-server -y
#
##systemctl enable mysqld
##systemctl restart mysqld
#
##mysql_secure_installation --set-root-pass RoboShop@1
#
##!/bin/bash
#
#dnf install mysql-server -y
#
#systemctl enable mysqld
#systemctl restart mysqld
#
## Root password already set, so update script to use password
#mysql -uroot -pRoboShop@1 <<EOF
#ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'RoboShop@1';
#FLUSH PRIVILEGES;
#EOF
#
- name: MySQL Setup
  hosts: all
  become: true
  tasks:
    - name: Install MySQL Server
      ansible.builtin.dnf:
        name: mysql-server
        state: present

    - name: Restart MongoDB service
      ansible.builtin.systemd_service:
        state: restarted
        name: mongod
        enabled: true

    - name: Setup SQL Root Password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1
