##dnf install mysql-server -y
#
##systemctl enable mysqld
##systemctl restart mysqld
#
##mysql_secure_installation --set-root-pass RoboShop@1
#
##!/bin/bash
#
#dnf install mysql-server -y
#
#systemctl enable mysqld
#systemctl restart mysqld
#
## Root password already set, so update script to use password
#mysql -uroot -pRoboShop@1 <<EOF
#ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'RoboShop@1';
#FLUSH PRIVILEGES;
#EOF
#

- name: My SQL Server Setup
  hosts: all
  become: true
  tasks:
    - name: Install the MySQL Repository Package
      ansible.builtin.dnf:
        # This URL is for RHEL 9; adjust if you are using RHEL 8
        name: https://dev.mysql.com/get/mysql80-community-release-el9-1.noarch.rpm
        state: present
        disable_gpg_check: true

    - name: Install MySQL Server
      ansible.builtin.dnf:
        name: mysql-community-server
        state: latest



