##dnf install mysql-server -y
#
##systemctl enable mysqld
##systemctl restart mysqld
#
##mysql_secure_installation --set-root-pass RoboShop@1
#
##!/bin/bash
#
#dnf install mysql-server -y
#
#systemctl enable mysqld
#systemctl restart mysqld
#
## Root password already set, so update script to use password
#mysql -uroot -pRoboShop@1 <<EOF
#ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'RoboShop@1';
#FLUSH PRIVILEGES;
#EOF
#

- name: Oracle MySQL Server Setup (Offline)
  hosts: all
  become: true
  tasks:
    - name: Download MySQL RPM from internal repo
      ansible.builtin.get_url:
        url: http://repo.internal/mysql/mysql-community-server.rpm
        dest: /tmp/mysql-community-server.rpm

    - name: Enable and start MySQL
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes




