#dnf module disable redis -y
#dnf module enable redis:7 -y
#
#dnf install redis -y
#
#sed -i -e '/protected-mode/ c protected-mode no' -e 's/127.0.0.1/0.0.0.0/' /etc/redis/redis.conf
#
#systemctl enable redis
#systemctl restart redis
#
- name: Redis Setup – Rocky Linux 9 / 10
  hosts: all
  become: true

  tasks:

    - name: Enable CRB repository
      ansible.builtin.command: dnf config-manager --set-enabled crb
      changed_when: false

    - name: Install EPEL repository
      ansible.builtin.dnf:
        name: epel-release
        state: present

    - name: Clean DNF cache
      ansible.builtin.command: dnf clean all
      changed_when: false

    - name: Install Redis
      ansible.builtin.dnf:
        name: redis
        state: present

    # ---------------- REDIS CONFIGURATION ----------------

    - name: Configure Redis bind address
      ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: '^bind .*'
        replace: 'bind 0.0.0.0'

    - name: Disable protected mode (for internal network access)
      ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: '^protected-mode yes'
        replace: 'protected-mode no'

    - name: Enable systemd supervision
      ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: '^supervised no'
        replace: 'supervised systemd'

    - name: Ensure Redis listens on default port
      ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: '^port .*'
        replace: 'port 6379'

    # ---------------- FIREWALL ----------------

    - name: Open Redis port in firewall
      ansible.builtin.firewalld:
        port: 6379/tcp
        permanent: yes
        state: enabled
        immediate: yes

    # ---------------- SERVICE ----------------

    - name: Enable and restart Redis service
      ansible.builtin.systemd:
        name: redis
        enabled: yes
        state: restarted




