- name: Shipping Setup
  hosts: all
  become: true

  vars:
    mysql_host: mysql-dev.kiranpanchavati.online
    mysql_user: roboshop
    mysql_password: RoboShop@1

    # SQL files must exist on CONTROL NODE
    db_schema_path: /root/Ansible/Ansible-RoboShop-V1/db/schema.sql
    db_user_path: /root/Ansible/Ansible-RoboShop-V1/db/app-user.sql
    db_master_path: /root/Ansible/Ansible-RoboShop-V1/db/master-data.sql

  tasks:
    # ---------------- BASIC SETUP ----------------

    - name: Install Maven
      ansible.builtin.dnf:
        name: maven
        state: present

    - name: Install required utilities
      ansible.builtin.dnf:
        name:
          - unzip
          - tar
        state: present

    - name: Create roboshop user
      ansible.builtin.user:
        name: roboshop

    - name: Create /app directory
      ansible.builtin.file:
        path: /app
        state: directory
        owner: roboshop
        group: roboshop

    - name: Download and extract shipping application
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
        dest: /app
        remote_src: yes
        owner: roboshop
        group: roboshop

    - name: Ensure /app is owned by roboshop
      ansible.builtin.file:
        path: /app
        owner: roboshop
        group: roboshop
        recurse: true

    # ---------------- BUILD APPLICATION ----------------

    - name: Build shipping application
      ansible.builtin.shell: |
        mvn clean package spring-boot:repackage -DskipTests
        ls -l target/
        if ls target/*.jar.original 1> /dev/null 2>&1; then
          mv target/*.jar.original shipping.jar
        else
          mv target/*.jar shipping.jar
        fi
      args:
        chdir: /app
      become_user: roboshop
      async: 1800
      poll: 20

    # ---------------- MYSQL CLIENT ----------------

    - name: Install MySQL client
      ansible.builtin.dnf:
        name: mysql
        state: present

    # ---------------- DATABASE TASKS (CONTROL NODE) ----------------

    - name: Verify DB schema file exists on control node
      ansible.builtin.stat:
        path: "{{ db_schema_path }}"
      delegate_to: localhost
      run_once: true
      register: schema_file

    - name: Fail if DB schema file is missing
      ansible.builtin.fail:
        msg: "DB schema file not found on control node: {{ db_schema_path }}"
      when: not schema_file.stat.exists
      delegate_to: localhost
      run_once: true

    - name: Load DB schema
      community.mysql.mysql_db:
        state: import
        name: all
        target: "{{ db_schema_path }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_host: "{{ mysql_host }}"
      delegate_to: localhost
      run_once: true
      vars:
        ansible_python_interpreter: /usr/bin/python3





    - name: Load master data
      community.mysql.mysql_db:
        state: import
        name: all
        target: "{{ db_master_path }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
        login_host: "{{ mysql_host }}"
      delegate_to: localhost
      run_once: true
      vars:
        ansible_python_interpreter: /usr/bin/python3

    # ---------------- SHIPPING SERVICE ----------------

    - name: Copy shipping service file
      ansible.builtin.copy:
        src: shipping.service
        dest: /etc/systemd/system/shipping.service

    - name: Enable and start shipping service
      ansible.builtin.systemd:
        name: shipping
        enabled: true
        state: restarted
        daemon_reload: true
