#dnf module disable nodejs -y
#dnf module enable nodejs:20 -y
#
#dnf install nodejs -y
#
#useradd roboshop
#cp user.service  /etc/systemd/system/user.service
#
#mkdir /app
#
#curl -L -o /tmp/user.zip https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
#cd /app
#unzip /tmp/user.zip
#
#cd /app
#npm install
#
#systemctl daemon-reload
#
#systemctl enable user
#systemctl restart user
- name: User Service Setup (Rocky Linux 10)
  hosts: all
  become: true

  tasks:
    ####################################################################
    # 1. Install NodeJS 20 (NodeSource – REQUIRED for Rocky 10)
    ####################################################################
    - name: Add NodeSource NodeJS 20 repository
      ansible.builtin.shell: |
        curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
      args:
        creates: /etc/yum.repos.d/nodesource-nodejs.repo

    ####################################################################
    # 2. Add MongoDB official repository
    ####################################################################
    - name: Add MongoDB repository
      ansible.builtin.copy:
        dest: /etc/yum.repos.d/mongodb-org.repo
        content: |
          [mongodb-org-7.0]
          name=MongoDB Repository
          baseurl=https://repo.mongodb.org/yum/redhat/9/mongodb-org/7.0/x86_64/
          gpgcheck=1
          enabled=1
          gpgkey=https://pgp.mongodb.com/server-7.0.asc

    ####################################################################
    # 3. Import MongoDB GPG key (MANDATORY)
    ####################################################################
    - name: Import MongoDB GPG key
      ansible.builtin.rpm_key:
        key: https://pgp.mongodb.com/server-7.0.asc
        state: present

    ####################################################################
    # 4. Install required packages
    ####################################################################
    - name: Install NodeJS, unzip, and mongosh
      ansible.builtin.dnf:
        name:
          - nodejs
          - unzip
          - mongodb-mongosh
        state: present

    ####################################################################
    # 5. Create roboshop user
    ####################################################################
    - name: Create roboshop user
      ansible.builtin.user:
        name: roboshop
        create_home: yes

    ####################################################################
    # 6. Copy User service file
    ####################################################################
    - name: Copy User systemd service file
      ansible.builtin.copy:
        src: user.service
        dest: /etc/systemd/system/user.service

    ####################################################################
    # 7. Create /app directory
    ####################################################################
    - name: Create /app directory
      ansible.builtin.file:
        path: /app
        state: directory
        owner: roboshop
        group: roboshop

    ####################################################################
    # 8. Download and extract User application
    ####################################################################
    - name: Download and extract User application code
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
        dest: /app
        remote_src: yes
        owner: roboshop
        group: roboshop

    ####################################################################
    # 9. Install NodeJS dependencies
    ####################################################################
    - name: Install NodeJS dependencies
      ansible.builtin.command: npm install
      args:
        chdir: /app
      become_user: roboshop

    ####################################################################
    # 10. Reload systemd
    ####################################################################
    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    ####################################################################
    # 11. Enable and restart User service
    ####################################################################
    - name: Enable and restart User service
      ansible.builtin.systemd:
        name: user
        state: restarted
        enabled: yes



