#dnf module disable nodejs -y
#dnf module enable nodejs:20 -y
#
#dnf install nodejs -y
#
#useradd roboshop
#cp user.service  /etc/systemd/system/user.service
#
#mkdir /app
#
#curl -L -o /tmp/user.zip https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
#cd /app
#unzip /tmp/user.zip
#
#cd /app
#npm install
#
#systemctl daemon-reload
#
#systemctl enable user
#systemctl restart user


- name: User Setup (Rocky Linux 10)
  hosts: all
  become: true

  tasks:
    - name: Install NodeSource NodeJS 20 repo
      ansible.builtin.shell: |
        curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -

    - name: Install NodeJS, Unzip, and Mongosh
      ansible.builtin.dnf:
        name:
          - nodejs
          - unzip
          - mongodb-mongosh
        state: present

    - name: Create roboshop user
      ansible.builtin.user:
        name: roboshop
        create_home: yes

    - name: Copy User service file
      ansible.builtin.copy:
        src: user.service
        dest: /etc/systemd/system/user.service

    - name: Create /app directory
      ansible.builtin.file:
        path: /app
        state: directory
        owner: roboshop
        group: roboshop

    - name: Download and extract User code
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
        dest: /app
        remote_src: yes
        owner: roboshop
        group: roboshop

    - name: Install NodeJS dependencies
      ansible.builtin.command: npm install
      args:
        chdir: /app
      become_user: roboshop

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable & restart User service
      ansible.builtin.systemd:
        name: user
        state: restarted
        enabled: yes

