#dnf module disable nodejs -y
#dnf module enable nodejs:20 -y
#
#dnf install nodejs -y
#
#useradd roboshop
#cp user.service  /etc/systemd/system/user.service
#
#mkdir /app
#
#curl -L -o /tmp/user.zip https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
#cd /app
#unzip /tmp/user.zip
#
#cd /app
#npm install
#
#systemctl daemon-reload
#
#systemctl enable user
#systemctl restart user

- name: User Setup
  hosts: all
  become: true
  tasks:
    - name: Disable NodeJS default module
      ansible.builtin.dnf:
        name: nodejs
        state: absent
      # Sometimes required to clear conflicts before enabling a stream

    - name: Install NodeJS 20
      ansible.builtin.dnf:
        name: '@nodejs:20'
        state: present

    - name: Add the user 'roboshop'
      ansible.builtin.user:
        name: roboshop

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download and extract app content
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
        dest: /app
        remote_src: yes
      notify: Restart Catalogue # Only restart if code changes

    - name: Install packages based on package.json
      community.general.npm:
        path: /app

    - name: Copy User Service file
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/user.service

    - name: Enable User service
      ansible.builtin.systemd_service:
        name: user
        enabled: true
        daemon_reload: true

  handlers:
    - name: Restart User
      ansible.builtin.systemd_service:
        name: user
        state: restarted